x-backend-cache: &backend-cache
  cache_from:
    - type=gha,scope=${CI_CACHE_SCOPE:-backend}
  cache_to:
    - type=gha,scope=${CI_CACHE_SCOPE:-backend},mode=max

x-frontend-cache: &frontend-cache
  cache_from:
    - type=gha,scope=${CI_CACHE_SCOPE:-frontend}
  cache_to:
    - type=gha,scope=${CI_CACHE_SCOPE:-frontend},mode=max

services:
  migrate:
    build:
      <<: *backend-cache
  api:
    build:
      <<: *backend-cache
  lint:
    build:
      <<: *backend-cache
  unit-test:
    build:
      <<: *backend-cache
  integration-test:
    build:
      <<: *backend-cache
  synthetic-generate:
    build:
      <<: *backend-cache
  synthetic-validate:
    build:
      <<: *backend-cache
  synthetic-import:
    build:
      <<: *backend-cache
  frontend:
    build:
      <<: *frontend-cache
  frontend-lint:
    build:
      <<: *frontend-cache
  frontend-test:
    build:
      <<: *frontend-cache
